services:
  jam_db:
    container_name: jam_db
    image: postgres:latest
    shm_size: 500mb
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=jammer
      - POSTGRES_DB=jam_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jammer -d jam_db -p 5432 -h localhost"] 
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      jam_db:
        condition: service_healthy
        restart: true