FROM debian:bookworm 

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends clang pkg-config libssl-dev curl ca-certificates git

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly\
  && rm -rf /var/lib/apt/lists/* 

ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install cargo-binstall --locked
RUN cargo-binstall cargo-leptos -y --version "0.2.28"
RUN cargo install sqlx-cli --locked

ENV CARGO_HOME=/root/.cargo
ENV RUSTUP_HOME=/root/.rustup
ENV RUST_BACKTRACE=full

RUN rustup target add wasm32-unknown-unknown

ENV RUSTUP_HOME=/app/.rustup